
#require no-eden


  $ export HGIDENTITY=sl
  $ configure modern

  $ export HG_TEST_INTERNALCONFIG="$TESTTMP/test_hgrc"
  $ cat > test_hgrc <<EOF
  > [section]
  > key=✓
  > EOF

  $ sl init client
  $ cd client

Verify it can be manually generated

  $ sl debugrefreshconfig
  $ cat .sl/hgrc.dynamic
  # version=* (glob)
  # reponame=* (glob)
  # canary=None
  # username=
  # Generated by `sl debugrefreshconfig` - DO NOT MODIFY
  [section]
  key=✓
  
  $ sl config section.key
  ✓
