// @generated SignedSource<<a946b19b1a71f444ac8b2c8216e9f18d>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/shadow_traffic/shadow_traffic.thrift
//
// Source: https://www.internalfb.com/code/configerator/[master]/source/scm/mononoke/shadow_traffic/shadow_traffic.thrift
/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This software may be used and distributed according to the terms of the
 * GNU General Public License version 2.
 */

package "meta.com/scm/mononoke/shadow_traffic"

namespace py3 scm.mononoke.shadow_traffic
namespace py scm.mononoke.shadow_traffic.shadow_traffic

/// Configuration for shadow traffic forwarding from production Mononoke
/// to a shadow tier for pre-release validation and performance benchmarking.
struct ShadowTrafficConfig {
  /// Master switch. When false, no shadow traffic is forwarded.
  1: bool enabled = false;

  /// Sampling percentage: 0-100. 0 means disabled, 1 means forward 1% of
  /// requests, 100 means forward all requests.
  2: i64 sample_ratio = 0;

  /// Regex for paths to include. Empty string means include all paths.
  3: string path_include = "";

  /// Regex for paths to exclude. Matched after path_include.
  /// Default excludes write/mutation endpoints.
  4: string path_exclude = "/upload/|/land/|/set_bookmark";

  /// Base URL of the shadow tier (e.g. "https://shadow-mononoke.internal.tfbnw.net").
  /// Empty string means no target configured (forwarding disabled).
  5: string target_url = "";

  /// Maximum number of concurrent in-flight shadow requests.
  /// Provides backpressure to prevent unbounded task accumulation.
  6: i64 semaphore_permits = 100;

  /// Timeout in milliseconds for shadow-first mode.
  /// Only used when shadow_first is true.
  7: i64 shadow_first_timeout_ms = 5000;

  /// When true, use shadow-first mode: forward to shadow with timeout,
  /// use shadow response on success, fall back to local processing on failure.
  /// When false (default), use fire-and-forget shadow mode.
  8: bool shadow_first = false;
}
