load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbsource//tools/target_determinator/macros:ci.bzl", "ci")

oncall("scm_server_infra")

cpp_binary(
    name = "dummy",
    srcs = ["dummy.cpp"],
    labels = [ci.skip_target()],
    deps = [
        "//eden/mononoke/tests/mock_restricted_path:dummy_lib",
    ],
)
