load("@fbcode//cpe/nupkg_builder:nupkg.bzl", "nupkg")
load(
    "@fbcode//eden/fs:build_targets.bzl",
    "EDENFS_WINDOWS_DEPS",
    "make_rpm_features",
)
load("@fbcode//registry:defs.bzl", "rpm")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:rust_universal_binary.bzl", "rust_universal_binary")

oncall("scm_client_infra")

cpp_library(
    name = "config",
    headers = ["eden-config.h"],
    exported_deps = [
        "//common/base:build_info_values",
    ],
)

# Universal (x86_64 + arm64) binary targets for macOS packaging.
# rust_universal_binary works for both Rust and C++ executables.

rust_universal_binary(
    name = "edenfs_universal",
    source = "//eden/fs/service:edenfs",
)

rust_universal_binary(
    name = "edenfs_privhelper_universal",
    source = "//eden/fs/service:edenfs_privhelper",
)

rust_universal_binary(
    name = "eden-fb303-collector_universal",
    source = "//eden/fs/facebook:eden-fb303-collector",
)

rust_universal_binary(
    name = "eden_fsck_universal",
    source = "//eden/fs/inodes/fscatalog:eden_fsck",
)

rust_universal_binary(
    name = "trace_stream_universal",
    source = "//eden/fs/cli/trace:trace_stream",
)

rust_universal_binary(
    name = "edenfsctl_universal",
    source = "//eden/fs/cli_rs/edenfsctl:edenfsctl",
)

rust_universal_binary(
    name = "edenfs_config_manager_rust_universal",
    source = "//eden/fs/config/facebook/config_manager_rs:edenfs_config_manager_rust",
)

rust_universal_binary(
    name = "edenfs_monitor_universal",
    source = "//eden/fs/monitor:edenfs_monitor",
)

rust_universal_binary(
    name = "eden_apfs_mount_helper_universal",
    source = "//eden/scm/exec/eden_apfs_mount_helper:eden_apfs_mount_helper",
)

rpm.builder(
    name = "fb-eden",
    # We are setting up conveyor+slowroll after which we can much lower this
    # limit. A higher limit is required for now to avoid weekly breakages as in
    # S209761.
    autoclean_keep_versions = 200,
    buck_opts = rpm.buck_opts(
        config = {
            # split-dwarf is required for reduce binary size
            "fbcode.split-dwarf": "true",
        },
    ),
    configurations = [
        rpm.configuration(
            arch = "x86_64",
            os = "linux",
        ),
        rpm.configuration(
            arch = "aarch64",
            os = "linux",
        ),
        rpm.configuration(
            arch = "noarch",
            os = "mac",
            repo = "darwin/any",
        ),
    ],
    features = make_rpm_features(),
    summary = "Source control aware virtual filesystem",
)

# TODO(T75318904): clean up the old packages once conveyor+slowroll is in
#                  place.
rpm.builder(
    name = "fb-eden-test",
    # We are setting up conveyor+slowroll after which we can much lower this
    # limit. A higher limit is required for now to avoid weekly breakages as in
    # S209761.
    autoclean_keep_versions = 200,
    buck_opts = rpm.buck_opts(
        config = {
            # split-dwarf is required for reduce binary size
            "fbcode.split-dwarf": "true",
        },
    ),
    configurations = [
        rpm.configuration(
            arch = "x86_64",
            os = "linux",
        ),
        rpm.configuration(
            arch = "aarch64",
            os = "linux",
        ),
        rpm.configuration(
            arch = "noarch",
            os = "mac",
            repo = "darwin/any",
        ),
    ],
    features = make_rpm_features(),
    summary = "Source control aware virtual filesystem",
)

nupkg.builder(
    name = "fb-eden-windows",
    chocolatey_install_script = "facebook/packaging/chocolateyinstall.ps1",
    chocolatey_uninstall_script = "facebook/packaging/chocolateyuninstall.ps1",
    compatible_with = [
        "ovr_config//os:windows",
    ],
    # @lint-ignore BUCKLINT target-level oncall is required here
    oncall = "scm_client_infra",
    summary = "Source control aware virtual filesystem",
    deps = EDENFS_WINDOWS_DEPS,
)

# TODO: Remove this once we have conveyor+slowroll in place.
nupkg.builder(
    name = "fb-eden-test-windows",
    chocolatey_install_script = "facebook/packaging/chocolateyinstall.ps1",
    chocolatey_uninstall_script = "facebook/packaging/chocolateyuninstall.ps1",
    compatible_with = [
        "ovr_config//os:windows",
    ],
    # @lint-ignore BUCKLINT target-level oncall is required here
    oncall = "scm_client_infra",
    summary = "Source control aware virtual filesystem",
    deps = EDENFS_WINDOWS_DEPS,
)

python_binary(
    name = "generate_version_release",
    main_src = "scripts/generate_version_release.py",
)
