load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "path_hash",
    srcs = glob([
        "src/**/*.rs",
    ]),
    deps = [
        "fbsource//third-party/rust:bincode",
        "//common/rust/shed/sql:sql",
        "//eden/mononoke/mononoke_types:mononoke_types",
    ],
)
