load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "shadow_forwarder",
    srcs = glob(["src/**/*.rs"]),
    allow_oss_build = False,
    autocargo = {"ignore_rule": True},
    named_deps = {
        "shadow_traffic_config": "//configerator/structs/scm/mononoke/shadow_traffic:shadow_traffic-rust",
    },
    test_deps = [
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:gotham",
        "fbsource//third-party/rust:gotham_derive",
        "fbsource//third-party/rust:http",
        "fbsource//third-party/rust:http-body-util",
        "fbsource//third-party/rust:rand",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:reqwest",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "//common/rust/shed/cached_config:cached_config",
        "//common/rust/shed/stats:stats",
        "//eden/mononoke/common/gotham_ext:gotham_ext",
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
    ],
)
