load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "iterhelpers",
    srcs = glob(["src/*.rs"]),
    test_deps = [
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
    ],
)
